export const EXAM_STATES = {
  DRAFT: 'DRAFT',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  PREPARATION: 'PREPARATION',
  SCHEDULE_PUBLISHED: 'SCHEDULE_PUBLISHED',
  EVALUATION: 'EVALUATION',
  PUBLISHED: 'PUBLISHED',
  CANCELLED: 'CANCELLED',
} as const;

export type ExamState =
  (typeof EXAM_STATES)[keyof typeof EXAM_STATES];
