export const ROLES = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  INSTITUTION_ADMIN: 'INSTITUTION_ADMIN',
  EXAM_CONTROLLER: 'EXAM_CONTROLLER',
  DEPARTMENT_ADMIN: 'DEPARTMENT_ADMIN',
  FACULTY: 'FACULTY',
  INVIGILATOR: 'INVIGILATOR',
  STUDENT: 'STUDENT',
  AUDITOR: 'AUDITOR',
} as const;

export type Role =
  (typeof ROLES)[keyof typeof ROLES];
